# -*- coding: utf-8 -*-
"""Image Swapp Complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDL0z790Ka4rrsn35AeAQDlOuHo6UyBm
"""

!pip install insightface onnxruntime-gpu opencv-python pillow matplotlib -q

import cv2
import insightface
from insightface.app import FaceAnalysis
from insightface.model_zoo import get_model
from google.colab.patches import cv2_imshow
from google.colab import files
import urllib.request

app = FaceAnalysis(name='buffalo_l')

app.prepare(
    ctx_id=0,
    det_size=(640, 640)
)

!wget https://github.com/deepinsight/insightface/releases/download/v0.7/inswapper_128.onnx

swapper = get_model(
    'inswapper_128.onnx',
    download=False,
)
#

uploaded = files.upload()

source_img = cv2.imread("/content/19501-1920x1080-desktop-full-hd-virat-kohli-wallpaper.jpg")
target_img = cv2.imread("/content/642241-dhoni-wallpaper-top-free-dhoni-background.jpg")

source_faces = app.get(source_img)
target_faces = app.get(target_img)

print("Source Faces:", len(source_faces))
print("Target Faces:", len(target_faces))

result = swapper.get(
    target_img,
    target_faces[0],
    source_faces[0],
    paste_back=True
)

result_rgb = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)

import matplotlib.pyplot as plt
plt.figure(figsize=(8,8))
plt.imshow(result_rgb)
plt.axis("off")
plt.title("AI Face Swap Output")
plt.show()

